"""add notification modified version

Revision ID: 1a882dc11aa4
Revises: d297eff1607b
Create Date: 2025-11-11 09:41:19.242630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a882dc11aa4'
down_revision: Union[str, Sequence[str], None] = 'd297eff1607b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('actor_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('actor_name', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('target_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('message_preview', sa.String(length=255), nullable=True))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['target_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('notifications', 'message_preview')
    op.drop_column('notifications', 'conversation_id')
    op.drop_column('notifications', 'target_id')
    op.drop_column('notifications', 'actor_name')
    op.drop_column('notifications', 'actor_id')
    # ### end Alembic commands ###
