"""sync user model columns

Revision ID: 3bdd15ac9158
Revises: 583d7efbe75a
Create Date: 2025-11-04 15:39:57.722183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdd15ac9158'
down_revision: Union[str, Sequence[str], None] = '583d7efbe75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('last_edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('relationship_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'relationship_status')
    op.drop_column('users', 'preference')
    op.drop_column('profiles', 'last_edited_at')
    # ### end Alembic commands ###
