"""add unmatched_at and reason again

Revision ID: 676b1e79a826
Revises: 9454a1fff65b
Create Date: 2025-11-08 16:38:41.207898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676b1e79a826'
down_revision: Union[str, Sequence[str], None] = '9454a1fff65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('unmatched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'reason')
    op.drop_column('matches', 'unmatched_at')
    # ### end Alembic commands ###
