"""add views and likes tables to match_model

Revision ID: 9ba5ee19d635
Revises: 8bd305d3517d
Create Date: 2025-11-06 12:27:19.037629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba5ee19d635'
down_revision: Union[str, Sequence[str], None] = '8bd305d3517d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('liker_id', sa.UUID(), nullable=False),
    sa.Column('liked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_like_liker_liked', 'likes', ['liker_id', 'liked_id'], unique=True)
    op.create_table('views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=False),
    sa.Column('viewed_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['viewed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_view_viewed_id', 'views', ['viewed_id'], unique=False)
    op.create_index('idx_view_viewer_id', 'views', ['viewer_id'], unique=False)
    op.create_index('idx_match_user_target', 'matches', ['user_id', 'target_id'], unique=True)
    op.add_column('reports', sa.Column('message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'messages', ['message_id'], ['id'])
    op.create_index('idx_swipe_swiper_swiped', 'swipes', ['swiper_id', 'swiped_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_swipe_swiper_swiped', table_name='swipes')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'message_id')
    op.drop_index('idx_match_user_target', table_name='matches')
    op.drop_index('idx_view_viewer_id', table_name='views')
    op.drop_index('idx_view_viewed_id', table_name='views')
    op.drop_table('views')
    op.drop_index('idx_like_liker_liked', table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
