"""Add indexes for messages table

Revision ID: c6e237f91259
Revises: 3bdd15ac9158
Create Date: 2025-11-05 14:34:02.575198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e237f91259'
down_revision: Union[str, Sequence[str], None] = '3bdd15ac9158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_messages_conversation', 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    op.create_index('idx_messages_unread', 'messages', ['receiver_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_unread', table_name='messages')
    op.drop_index('idx_messages_conversation', table_name='messages')
    # ### end Alembic commands ###
