"""add notified_at to notifications

Revision ID: dfb7aa430725
Revises: 1a882dc11aa4
Create Date: 2025-11-12 11:34:23.497953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb7aa430725'
down_revision: Union[str, Sequence[str], None] = '1a882dc11aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_notifications_notified_at'), 'notifications', ['notified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_notified_at'), table_name='notifications')
    op.drop_column('notifications', 'notified_at')
    # ### end Alembic commands ###
